# Generated by Django 3.2 on 2021-04-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display', models.CharField(max_length=255, verbose_name='Display type')),
                ('resolution', models.CharField(max_length=255, verbose_name='Display option')),
                ('battery', models.CharField(max_length=255, verbose_name='Battery')),
                ('frontal_camera', models.CharField(max_length=255, verbose_name='Front camera')),
                ('main_camera', models.CharField(max_length=255, verbose_name='Camera')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display', models.CharField(max_length=255, verbose_name='Display type')),
                ('ram', models.CharField(max_length=255, verbose_name='RAM')),
                ('video', models.CharField(max_length=255, verbose_name='Video cart')),
                ('processor', models.CharField(max_length=255, verbose_name='Processor')),
                ('os', models.CharField(max_length=255, verbose_name='OS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
